import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

from backend.database import db_connection
from backend.models import UserProfile
from backend.retrieval_service import RetrievalService
from backend.rules import evaluate


def main():
    query = input("\nEnter your situation:\n> ").strip()

    if not query:
        print("No situation provided.")
        return

    # Example profile.
    # We will later replace this with the profile generated by
    # the real IntakeAgent/LLM pipeline.
    profile = UserProfile(
        age=35,
        gender="male",
        state="uttar pradesh",
        residence="rural",
        annual_income=100000,
        category="general",
        occupation="farmer",
        education_level="ug",
        has_bpl_card=True,
        owns_cultivable_land=True,
        owns_pucca_house=False,
        has_bank_account=True,
        has_lpg_connection=False,
        income_tax_payer=False,
        government_employee=False,
    )

    with db_connection() as conn:
        retrieval = RetrievalService(conn)

        results = retrieval.retrieve(
            query,
            top_k=10,
            min_similarity=0.0,
        )

        print("\n" + "=" * 70)
        print("RAG RESULTS")
        print("=" * 70)

        if not results:
            print("No schemes retrieved.")
            return

        for i, scheme in enumerate(results, 1):
            print(
                f"{i:2}. "
                f"[{scheme.get('similarity', 0):.3f}] "
                f"{scheme.get('name', scheme.get('id'))}"
            )

        print("\n" + "=" * 70)
        print("RAG → RULE ENGINE")
        print("=" * 70)

        for i, scheme in enumerate(results, 1):
            rules = scheme.get("rules", {})

            status, reasons, unknowns = evaluate(
                profile,
                rules,
            )

            print(f"\n{i}. {scheme.get('name', scheme.get('id'))}")
            print(f"   ID:     {scheme.get('id')}")
            print(f"   Score:  {scheme.get('similarity', 0):.3f}")
            print(f"   Status: {status}")

            if reasons:
                print("   Reasons:")
                for reason in reasons:
                    print(f"     - {reason}")

            if unknowns:
                print("   Unknown:")
                for unknown in unknowns:
                    print(f"     - {unknown}")


if __name__ == "__main__":
    main()