"""Verification Agent — provenance for every link we show.

URLs are NEVER generated by an LLM. They come from the curated database,
each with a last-verified date. With VERIFY_LINKS=1 this agent also
live-checks each official URL before presenting it (needs internet;
kept off by default so demos work offline).
"""
import asyncio
import os

import requests

from backend.agents.base import BaseAgent, AgentContext


HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}


def _check(url: str) -> bool:
    try:
        r = requests.head(url, timeout=5, allow_redirects=True, headers=HEADERS)
        if r.status_code >= 400:  # some gov servers reject HEAD; retry GET
            r = requests.get(url, timeout=8, stream=True, headers=HEADERS)
        return r.status_code < 400
    except requests.exceptions.SSLError:
        # some gov servers send incomplete cert chains; liveness check only
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        try:
            r = requests.get(url, timeout=8, stream=True, headers=HEADERS, verify=False)
            return r.status_code < 400
        except requests.RequestException:
            return False
    except requests.RequestException:
        return False


class VerificationAgent(BaseAgent):
    name = "verification"
    label = "Verification Agent"
    emoji = "🔗"

    async def run(self, ctx: AgentContext):
        relevant = [f for f in ctx.findings if f.status in ("eligible", "possible")]
        urls = sorted({f.official_url for f in relevant})
        yield self.event(f"All {len(urls)} links come from the curated official-source database")
        await self.pause()

        if os.getenv("VERIFY_LINKS") == "1":
            yield self.event("Live-checking official portals...")
            results = await asyncio.gather(*[asyncio.to_thread(_check, u) for u in urls])
            alive = dict(zip(urls, results))
            for f in ctx.findings:
                f.link_alive = alive.get(f.official_url)
            dead = [u for u, ok in alive.items() if not ok]
            if dead:
                yield self.event(f"⚠ {len(dead)} portal(s) unreachable right now: {', '.join(dead)}")
            else:
                yield self.event(f"All {len(urls)} official portals responded ✓")
        else:
            yield self.event("Live link-check skipped (set VERIFY_LINKS=1 to enable)")
        await self.pause()
        yield self.event("Sources verified — every card cites its official portal", state="done")
